module Hardcoded ( varBuiltins ) where

import ClassyPrelude

-- since we don't fully parse all variables yet, hard-code some to get
-- past the parser verification process.
--
-- this list needs to be cleaned up.
varBuiltins :: [String]
varBuiltins = [ "SynergyBonus"
              , "Reputation"
              , "DomainLVL"
              , "DomainPowerTimes"
              , "DomainAbilityTriggerLVL"
              , "Insanity"
              , "AlignmentAuraBase"
              , "ATWILL"
              , "AllowHolyAvenger"
              , "FlurryOfFistsExtraAttacks"
              , "FlurryAttacks"
              , "FlurryPenalty"
              , "FlurryBABBonus"
              , "FlurryExtraAttacks"
              , "MeditantFlurryBABBonus"
              , "MeditantFlurryExtraAttacks"
              , "MindBladeRANGE"
              , "MindBladeDAMAGESIZEADJ"
              , "MindBladeEnchantment"
              , "COUNT[EQTYPE.ARMOR.EQUIPPED]" -- ??
              , "SHIELDACCHECK"
              , "ACCHECK"
              , "EQHANDS"
              , "CompanionExtraHD"
              , "SKILLRANK=Bluff"
              , "AntipaladinLVL"
              , "PaladinLvl"
              , "PsiBladeDamage"
              , "PsiBladeEnhancement"
              , "PsiShieldDefense"
              , "PsiCrystalLVL"
              , "PCrystalLevel"
              , "STRSCORE"
              , "ShieldBonus"
              , "SamuraiArmorBonus"
              , "GunneryPenalty"
              , "RobotSpeedIncreaseCost"
              , "RobotPurchaseDC"
              , "InventionLevel"
              , "BaseInventionLevel"
              , "TrapCR"
              , "PSIONLEVEL"
              , "ShimmerMailACBonus"
              , "GunGlyphMarksman"
              , "MAXVEHICLEMODS"
              , "MAX_LEVEL"
              , "DMGDIE"
              , "ArrowEnhancement"
              , "EnchantArrow"
              , "%CHOICE" -- TODO: probably not right
              , "CHOICE"
              , "%LIST"
              , "CRITMULT"
              , "MASTER"
              , "MasterLVL"
              , "MOVEBASE"
              , "DEXSCORE"
              , "INTSCORE"
              , "CHASCORE"
              , "WISSCORE"
              , "STAT.3.BASE" -- ?
              , "STAT.0.BASE" -- ?
              , "ARMOR.SHIELD.EQUIPPED.ACBONUS"
              , "SPELLFAILURE"
              , "CASTERLEVEL"
              , "MXDXEN"
              , "MODEQUIPMAXDEX"
              , "FamiliarBonusHP"
              , "FeedbackDamage"
              , "PowerDrainTime"
              , "ItemEgo"
              , "SeverisEnhancementBonus"
              , "Severis"
              , "sDefenseFlat"
              , "sDefenseAuto"
              , "sDefense"
              , "sInit"
              , "sHard"
              , "sHDpre"
              , "sHDpost"
              , "sHDpost"
              , "sPilotCB"
              , "sPilotDEX"
              , "sGunnerAB"
              , "sTacSpeed"
              , "sLength"
              , "sSize"
              , "sGrapple"
              , "sWeight"
              , "sTargetingSB"
              , "sCrewTrain"
              , "sCrewNUM"
              , "sPass"
              , "sCargo"
              , "ShipTypeMod"
              , "sDefenseAuto"
              , "sGrapple"
              , "vcargo" -- ??
              , "vinit" -- ??
              , "vpass" -- ??
              , "vcrew" -- ??
              , "vmaneuver" -- ??
              , "vt_speed" -- ??
              , "v_max_speed" -- ??
              , "vdefense" -- ??
              , "vhard" -- ??
              , "vhpee" -- ??
              , "m_hp" -- ??
              , "unit" -- ??
              , "InventionLevel"
              , "SIZE"
              , "HEADPLUSTOTAL"
              , "ALTPLUSTOTAL"
              , "PLUSTOTAL"
              , "VEHICLEWOUNDPOINTS"
              , "AlchemistBombAdditionalDice"
              , "DancingRobesArmorBonus"
              , "ArmorDPValue"
              , "DissonanceEnhancementBonusMain"
              , "DissonanceEnhancementBonusAlt"
              -- COST only vars?
              , "BASECOST"
              , "SIZE"
              , "%CASTERLEVEL"
              , "%CHARGES"
              , "%SPELLLEVEL"
              , "%SPELLCOST"
              , "%SPELLXPCOST"
              , "SPELLLEVEL"
              -- end
              , "BAB"
              , "WT"
              , "TL"
              , "CL"
              , "HD"
              , "INT"
              , "DEX"
              , "STR"
              , "CON"
              , "WIS"
              , "CHA"
              , "NOB"
              ]
